### ISSUE TITLE
Meta: First Release

### ISSUE THREAD

**Issue by willscott** [oasislabs/web3c.js#12]
* [x] [Deployment](https://github.com/oasislabs/web3c.js/issues/11) - 1 day
* [x] [Docs](https://github.com/oasislabs/web3c.js/issues/9) - 2 days 
* [x] [Wallet](https://github.com/oasislabs/web3c.js/issues/8) - 5 days
* [x] [Core Gateway Comms](https://github.com/oasislabs/web3c.js/issues/1) - 2 days once https://github.com/oasislabs/runtime-ethereum/issues/180 responds to pubkey calls
* [x] Encryption primitives - Done
* [x] [Building confidential contract interface from ABI](https://github.com/oasislabs/web3c.js/issues/5) - 5 days
